[build]
  # The directory where Netlify will look for the final build files
  publish = "build"
  # The command to run your build process
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
